apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-example
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: spring-boot-example   # Ensure this matches the labels below
  template:
    metadata:
      labels:
        app: spring-boot-example  # Ensure this matches the selector
    spec:
      containers:
        - name: spring-boot-example
          image: 'gcr.io/forward-lead-430417-g9/google_sample:v1'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-example
  labels:
    app: spring-boot-example    # Label consistent with the app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-example    # Matches the label of the pods
  type: LoadBalancer
